language: node_js
node_js:
    - 13.8.0
env:
    global:
        - PORT=3000
        - JWT_SECRET=supersecrettoken
        - MONGODB_URL=mongodb://127.0.0.1:27017/task-manager-api-test
services:
    - mongodb